#!/usr/bin/env ruby

if (ARGV & %w(-h --help)).any?
  puts "Usage: HandBrakeCLIBatch [preset OR source dir] [dest dir]"
  puts "Source and dest both default to ."
  exit
end

quality = ARGV[0] || "High Profile"
if ARGV[0] && File.exist?(ARGV[0])
  movies_dir = ARGV[0]
else
  movies_dir = Dir.pwd
end
dest_dir   = ARGV[1] || movies_dir

puts "Converting from"
puts "  #{movies_dir} to"
puts "  #{dest_dir}"
puts "  with preset '#{quality}'"

movies_glob = File.join(movies_dir, "**/*.{avi,mkv}")
Dir[movies_glob].each do |file|
  dest_dir  = File.dirname(file)
  new_file  = File.basename(file, File.extname(file)) + ".m4v"
  dest_file = File.join(dest_dir, new_file)

  if File.exist?(dest_file)
    STDERR.puts "Converted file already exists!\n  #{dest_file}"
    next
  else
    puts "Converting #{File.basename(dest_file)}"
  end


  cmd = %{HandBrakeCLI -v -i "#{file}" -o "#{dest_file}" --preset "#{quality}"}
  if ENV['DEBUG']
    puts cmd
    exit
  end
  system(cmd)
end
